//跨域代理前缀
// const API_PROXY_PREFIX='/api'
// const BASE_URL = process.env.NODE_ENV === 'production' ? process.env.VUE_APP_API_BASE_URL : API_PROXY_PREFIX
// const BASE_URL = process.env.VUE_APP_API_BASE_URL
const BASE_URL = "/api";
const BASE_URL2 = "/gas";
module.exports = {
  // LOGIN: `${BASE_URL}/login`,
  LOGIN: `${BASE_URL}/login`,
  ROUTES: `${BASE_URL}/routes`,
  GOODS: `${BASE_URL}/goods`,
  GOODS_COLUMNS: `${BASE_URL}/columns`,
  getPackets: `${BASE_URL}/culture-packet/getPackets`,
  EDIT_PACKETS: `${BASE_URL}/culture-packet/update`,
  DELETE_PACKETS: `${BASE_URL}/culture-packet/delete`,
  CREATE_PACKETS: `${BASE_URL}/culture-packet/insert`,
  COMMIT_PACKETS: `${BASE_URL}/culture-packet/commit`,
  GET_PRODUCTS: `${BASE_URL}/culture-product/getProducts`,
  DELETE_PRODUCTS: `${BASE_URL}/culture-product/delete`,
  GET_PRODUCTS_INFO: `${BASE_URL}/culture-product/getInfo`,
  INSERT_PRODUCTS: `${BASE_URL}/culture-product/insert`,
  GET_ADDRESS: `${BASE_URL}/culture-company-address/getAddress`,
  UPDATE_PRODUCTS: `${BASE_URL}/culture-product/update`,
  // GET_ORDER:`${BASE_URL}/culture-order/getOrders`,
  GET_ORDER: `${BASE_URL2}/CultureAdminController/getOrders`,
  GET_ORDER_INFO: `${BASE_URL}/culture-order/getInfo`,
  PICK_ORDER: `${BASE_URL}/culture-order/pickOrder`,
  GET_NEWS: `${BASE_URL}/culture-news/getNews`,
  RELEASE_NEWS: `${BASE_URL}/culture-news/releaseNews`,
  REBACK_NEWS: `${BASE_URL}/culture-news/withdrawNews`,
  DELETE_NEWS: `${BASE_URL}/culture-news/delete`,
  GET_COMPANY_ADDRESS: `${BASE_URL}/culture-company-address/getAddress`,
  INSERT_COMPANY_ADDRESS: `${BASE_URL}/culture-company-address/insertAddress`,
  UPDATE_COMPANY_ADDRESS: `${BASE_URL}/culture-company-address/update`,
  GET_COMPANY_ADDRESS_INFO: `${BASE_URL}/culture-company-address/getInfo`,
  DELETE_COMPANY_ADDRESS: `${BASE_URL}/culture-company-address/deleteAddress`,
  GET_COMPANY_ADDRESS_PRODUCT: `${BASE_URL}/culture-company-address/getAddressForProduct`,
  GET_COMPANY_INFO: `${BASE_URL}/culture-company/getInfo`,
  UPDATE_COMPANY_INFO: `${BASE_URL}/culture-company/update`,
  UPDATE_PASSWORD: `${BASE_URL}/culture-company-admin/updatePassword`,
  GET_NEWS_INFO: `${BASE_URL}/culture-news/getInfo`,
  UPLOAD_FILE: `${BASE_URL}/file/upload`,
  INSERT_NEWS: `${BASE_URL}/culture-news/insert`,
  UPDATE_NEWS: `${BASE_URL}/culture-news/update`,
  GET_HOME_INFO: `${BASE_URL}/home`,
  GET_PRODUCT_INFO: `${BASE_URL}/culture-product/getDetail`,
  GET_ORDER_DELIVERY: `${BASE_URL2}/CultureAdminController/getOrderDelivery`,
  DELIVER_GOODS: `${BASE_URL2}/CultureAdminController/deliverGoods`,
};
